apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: docker.io/mukeshjalwal/myapp:20250324043921-bdf7cef
#          imagePullPolicy: Always
          ports:
            - containerPort: 5000

